### ISSUE TITLE
Config test requires AADGroupScopingConfig, script uses AADGroupScopingFilter

### ISSUE THREAD

**Issue by StoobertB** [goodworkaround/AAD-Group-Writeback-Script#1]
https://github.com/goodworkaround/AAD-Group-Writeback-Script/blob/04269d3d55f294ad3c3fd36dfd99171bbaa85e91/Run.ps1#L63

When using "Filter" for the **AADGroupScopingMethod**, the config test will halt if the **AADGroupScopingConfig** parameter is not set, however in the Run script, the parameter passed to the filter is **AADGroupScopingFilter**, which unless explicitly set (and not documented) will create an empty filter, returning all groups, which could cause the entirety of Azure AD to be synced back.

**Comment by mariussm** [comment]
Thanks for the bug report. Bug squashed now 👍 

https://github.com/goodworkaround/AAD-Group-Writeback-Script/pull/2
