### ISSUE TITLE
Is there a use case for this script, if one is already using AAD Connect with Write Back enabled?

### ISSUE THREAD

**Issue by c3rberus** [goodworkaround/AAD-Group-Writeback-Script#13]
I recently started playing with the privileged access groups in PIM, I see a lot of potential to extend PIM to on-premise roles (domain admins, exchange admins, SQL admins, etc.).

My on-prem AAD Connect is configured with Group Write Back (v2) enabled, so any privileged access group changes are syncronized.

It seems that AAD Connect does what this script is doing, in that it looks at group membership in AAD and updates on-prem. Why would one use this? 

Would a case for this be, to be able to "sync" the PIM changes faster than the default 30 minutest that AAD Connect scheduler runs at?

**Comment by mariussm** [comment]
Hi @c3rberus, 

First of all, this script was made before Azure AD Connect had a writeback feature, second, it still have its use cases:

1. As you point out, it can sync faster than every 30 minutes, enabling PIM features to be more "live" (You will still have some AD replication wait times in AD, but you can actually have several instances of this script running in separate AD sites if you want, targeting a separate set of groups)
2. The script can support groups being added to domain admins, enterprise admins etc. These are domain local groups in AD, and are not supported by AAD Connect currently.

**Comment by c3rberus** [comment]
Thanks, that clarifies it for me; still has a good use case to cut back on sync time in case of using cloud PIM to manage groups being added to on-prem domain admins, etc...
