### ISSUE TITLE
Error when set AADGroupScopingMethod to "GroupMemberOfGroup"

### ISSUE THREAD

**Issue by martinyy108** [goodworkaround/AAD-Group-Writeback-Script#3]
I am getting error in attached screenshot when AADGroupScopingMethod is set to "GroupMemberOfGroup" and I can confirm the objectid of Azure AD group is correct.

Can you please provide some suggestions? Thanks a lot!

![Error1](https://user-images.githubusercontent.com/39147252/133722608-a370743e-d84f-47b8-b79b-a51687055053.PNG)

**Comment by martinyy108** [comment]
I worked this one out

**Comment by mariussm** [comment]
Awesome, feel free to pull request updated documentation if something was unclear :)
