### ISSUE TITLE
Not Setting $AccessToken

### ISSUE THREAD

**Issue by stevejbauer** [goodworkaround/AAD-Group-Writeback-Script#7]
When the AuthenticationMethod is set to “ClientCredentials” the line…

$AccessToken = Get-ClientCredentialsMSGraphAccessToken -ClientID $Config.ClientID -EncryptedSecret $Config.EncryptedSecret -TenantID $Config.TenantID is not setting 

Doesn’t seem to assign the AccessToken to the variable.

Instead it throughs an exception: 

When running verbose I get the following:

VERBOSE: POST https://login.microsoftonline.com//tenantID removed/oauth2/v2.0/token with -1-byte
payload
Write-Error : Cannot bind parameter 'Exception'. Cannot convert the
"{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named
https://login.microsoftonline.com/ was not found in the tenant named (removed). This can happen if the application has not
been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your
authentication request to the wrong tenant.\r\nTrace ID: 7243079b-097e-4325-a60d-4ccbea470000\r\nCorrelation ID:
c66fcdf7-8d67-4091-97fb-bb8df7105293\r\nTimestamp: 2022-04-28
21:37:35Z","error_codes":[500011],"timestamp":"2022-04-28 21:37:35Z","trace_id":"7243079b-097e-4325-a60d-4ccbea470000",
"correlation_id":"c66fcdf7-8d67-4091-97fb-bb8df7105293","error_uri":"https://login.microsoftonline.com/error?code=50001
1"}" value of type "System.Management.Automation.ErrorRecord" to type "System.Exception".
At C:\AAD-Group-Writeback-Script\AuthenticationMethods\ClientCredentials.psm1:77 char:95
+ ... ror when getting access token using client credentials" -Exception $_
+                                                                        ~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Error], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.WriteErrorCommand

C:\AAD-Group-Writeback-Script\Run.ps1 : Cannot bind argument to parameter 'Base64JWT' because it is null.
At line:1 char:1
+ .\run.ps1 -WhatIf -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Run.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Run.ps1

I have removed my tenant ID and name

Thanks for the help

**Comment by stevejbauer** [comment]
I tracked the issue down to the function Get-ClientCrentialsMSGraphAccesstoken.

the problem is when building the $body, for the scope the Login URL is used instead of the graph URL.

**Comment by mariussm** [comment]
Hi @stevejbauer , thanks for your report. Seems this was introduced when a PR was merged, in order to support other Azure clouds. I believe I have a fix in a branch:  https://github.com/goodworkaround/AAD-Group-Writeback-Script/tree/7-not-setting-accesstoken

Could you test it out and verify that it works? (Currently don't have an environment available for testing)

**Comment by stevejbauer** [comment]
It looked like the fixes work.  With our current configuration, the run.ps1 was able to login to the service account, etc.
