### ISSUE TITLE
Group object does not seem to anchor

### ISSUE THREAD

**Issue by evan-nemeth** [goodworkaround/AAD-Group-Writeback-Script#9]
Hi there,
Let me know if I'm overlooking a core functionality or intended use-case, but in my testing, once a group is written-back to on premise AD, at the next directory sync cycle the group is then replicated to Azure AD with a new object ID but the same display name. Is this not intended to be used in an environment where on premise groups are replicated to Azure?

-Evan

**Comment by mariussm** [comment]
Hi @evan-nemeth, you need to exempt the OU where you are writing back groups from Azure AD Connect synchronization. :) 

And yes, the point is that the group is synced to AD, and not OUT to Azure AD :)
